// This file is automatically generated. Do not edit it directly.
// A3 · Step 9 exception: the env guard below is hand-added and must be
// preserved — it makes a missing backend connection fail fast and legibly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Typed env access — Vite injects these at build time; either may be undefined
// if the environment isn't configured.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as
  | string
  | undefined;

// Fail fast, with a clear message, when the backend connection isn't configured.
// Left unguarded, a missing var surfaces deep inside the SDK as an opaque
// "Invalid URL" / "supabaseUrl is required" throw at the first call; this makes
// the boot failure obvious and actionable instead.
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  const missing = [
    !SUPABASE_URL ? 'VITE_SUPABASE_URL' : null,
    !SUPABASE_PUBLISHABLE_KEY ? 'VITE_SUPABASE_PUBLISHABLE_KEY' : null,
  ]
    .filter(Boolean)
    .join(', ');
  throw new Error(
    `Colors of Glory can't reach its backend: missing ${missing}. ` +
      `Set the variable(s) in your environment (.env) and reload.`,
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});